/*
 * SavingsAccount.java
 * Khair Ahmed , 040946481
 * CST8132 300 - OOP
 * Lab 9
 * July 24th, 2019
 * Dr. Mohammad Kadum
 * 
 * subclass of bank account acts contains information and performs fuctions specific to the savings account only
 * 
 * Class List:
 * Assign1.java
 * Bank.java
 * BankAccount.java
 * ChequingAccount.java
 * SavingsAccount.java
 * Person.java
 */
/***********************************************************************************************/
/**
 * 
 * subclass of bank account acts contains information and performs fuctions
 * specific to the savinfs account only
 * 
 * 
 * @author Khair Ahmed
 * @version 1.2
 * @since 1.8.0_191
 * @see BankAccount.java
 */

public class SavingsAccount extends BankAccount	 {

	/**
	 * SavingsAccount default constructor, that inherits 
	 * properties of {@link BankAccount}
	 */
	public SavingsAccount() {
		super();
	}
	/**
	 * Method goes prompts user for to enter all of the information required
	 * to create the SavingsAccount object
	 * @return true if account is added
	 * @return false if account is not added
	 * 
	 */
	public boolean addBankAccount(String firstNameField, String lastNameField,String phoneNumField, String emailAddressField) {
		//call to super class  addBankAccount() method
		super.addBankAccount(firstNameField, lastNameField,phoneNumField, emailAddressField);
		
		return true;
//		
		
	}
	/**
	 * adds the amount generated by the interest to the main balance
	 * 
	 */

	@Override
	public void monthlyAccountUpdate() {
		
	
			balance *= (1 + interestRate);
		
	}
	/**
	 * prints out user information for savings accounts and calls to super
	 */
	
	@Override
	public String toString() {
		return "s "+ super.toString() + " " + decimalFormat.format(this.minimumBalance) + " " + decimalFormat.format(this.interestRate);
		
	}

	
	/**
	 * sets the minimum balance and the interest rate for the accounts
	 * @param minimumBalance minimumbalance of the accounts
	 * @param interestRate interest rate of the account
	 */
	public void setValues(double minimumBalance, double interestRate) {
		this.minimumBalance= minimumBalance;
		this.interestRate = interestRate;
		
	}

}